apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: back
spec:
  replicas: {{ .Values.replicas }}  # Refers to replicas from values.yaml
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.repository }}/{{ .Values.tag }}  # Access image and tag from values.yaml
          ports:
            - containerPort: {{ .Values.containerPort }}  # Access containerPort from values.yaml
