apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: back
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.image }}/{{ .Values.tag }}
      ports:
        - containerPort: {{ .Values.containerPort }}