apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: {{ .Values.replicaCount }}  # Ensure the value matches your `values.yaml`
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.repository }}:{{ .Values.tag }}"  # Adjusted for Helm's repository and tag format
          ports:
            - containerPort: {{ .Values.containerPort }}
