apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: {{ .Values.type }}  # Ensure this is the correct templating syntax
  ports:
    - port: 80
      targetPort: {{ .Values.containerPort }}
  selector:
    app: frontend
