apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: {{ .Values.service.type }}  # Corrected for service type mapping in `values.yaml`
  ports:
    - port: 80
      targetPort: {{ .Values.containerPort }}
  selector:
    app: frontend
